version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express:test
    container_name: backend
    restart: always
    ports:
      - 5000:5000
    environment:
      DB_USER: "root"
      DB_PASSWORD: "example"
      DB_HOST: "mongo"
      DB_PORT: "27017"
